# Generated by Django 4.1.5 on 2023-12-25 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('exchange_id', models.CharField(max_length=255, unique=True)),
                ('spot_fee', models.FloatField(default=0.001)),
                ('future_fee', models.FloatField(default=0.0005)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge_bot.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangeapi',
            constraint=models.UniqueConstraint(fields=('user', 'exchange'), name='Same user cannot have api for the same exchange'),
        ),
    ]
